# Generated by Django 2.2.3 on 2019-07-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Pet',
        ),
    ]
