# Generated by Django 2.2.3 on 2019-07-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20190720_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='logo',
            new_name='photo',
        ),
    ]
